### ISSUE TITLE
crashed in exporting

### ISSUE THREAD

**Issue by lovelori** [weiyu666/RevitExportGltf#2]
导出时崩溃了。文件夹出了几种材质
<img width="911" alt="crash" src="https://user-images.githubusercontent.com/17640406/132821209-9304f73b-c81a-4791-b2c5-753388b7c9d5.png">

**Comment by weiyu666** [comment]
什么版本？导出应该没有什么问题的！你要跳进exporter.Export(view);里面执行 主要就在RevitExportGltfContext 类里面，看一下到底是在哪里出错啦~文件夹出了几种纹理贴图是正确的，但是它的命名是有特殊字符我是有过过滤过的。
