### ISSUE TITLE
.addin manifest file

### ISSUE THREAD

**Issue by cartosquare** [weiyu666/RevitExportGltf#3]
可以提供一个 .addin  manifest file的例子吗？

**Comment by cartosquare** [comment]
使用下面这个 manifest，运行的时候报错：

```
<?xml version="1.0" encoding="utf-8"?>
<RevitAddIns>
  <AddIn Type="Command">
    <Text>Commandx RevitExportGltf</Text>
    <Description>Some description for RevitExportGltf</Description>
    <Assembly>./RevitExportGltf/RevitExportGltf.dll</Assembly>
    <FullClassName>RevitExportGltf.Command</FullClassName>
    <ClientId>38555A79-E66E-49B6-8278-191F17E931B2</ClientId>
    <VendorId>_RTM</VendorId>
    <VendorDescription>Ryan T. McCullough</VendorDescription>
  </AddIn>
</RevitAddIns>
```
![revit-error](https://user-images.githubusercontent.com/6066346/146367888-5abfad50-62f3-4527-8649-3968b2e331d4.PNG)

**Comment by weiyu666** [comment]
已经提交最新的版本啦 https://github.com/weiyu666/RevitExportGltf/commit/950402a3db06c31aa72134299607e32963089503 
你可以再试试看，感觉就是revit二开 环境问题

**Comment by cartosquare** [comment]
> 已经提交最新的版本啦 [950402a](https://github.com/weiyu666/RevitExportGltf/commit/950402a3db06c31aa72134299607e32963089503) 你可以再试试看，感觉就是revit二开 环境问题

下载最新版本编译，使用libs/revit2020目录下的dll拷贝到plugin目录，还是有这个问题。。

**Comment by cartosquare** [comment]
![warn](https://user-images.githubusercontent.com/6066346/146629439-86721ed9-cc30-4eb3-9831-424ca37dd81d.PNG)

有可能是Export这个方法导致的错误？

**Comment by weiyu666** [comment]
编译出错?这种问题自己解决2018 2020 亲测好用! "此方法在 revit 2020 中已弃用，并将在下一版本的 revit 中删除，请使用 export(view) instaead"  是你本地版本的问题上面已经告诉你啦 看不懂?它api改了  你改成对应的就可以啦
