### ISSUE TITLE
关于材质

### ISSUE THREAD

**Issue by hbbliyong** [weiyu666/RevitExportGltf#4]
1.如果使用了凹凸贴图，怎么取出两张贴图？

**Comment by hbbliyong** [comment]
`  //取得Asset中贴图信息
                    var asset = FindTextureAsset(currentAsset as AssetProperty);
                    if (asset == null)
                    {
                        //textureFile找不到
                      //  return;
                    }`
这个地方不能直接return,不然他本身对的颜色都取不到了

**Comment by weiyu666** [comment]
一、不能直接return,你是怎么样做的?请教一下哈 看看你代码;
二、使用了凹凸贴图?我看了 revit的材质库是在你C盘下的autodesk的材质库 没看到凹凸贴图，如果你想要从基础的纹理贴图生成凹凸贴图就是一个后处理问题有相应的算法你可以直接生成或者建模的时候搞进去？

**Comment by hbbliyong** [comment]
1.这个return以后，else里面的basecolor就无法取到了
2.material.color取的是着色的颜色，好像无法取到外观的颜色
3.凹凸贴图应该有两张图片，一个是bump图，一个是纹理图，好像现在只能取到一个

**Comment by weiyu666** [comment]
1、这个return以后，basecolor获取不到很正常本来就没有呀！asset 都没有你就获取不到资源；
2、material.color取到的就是revit中构件本身的材质color（你可以查看构建本身材质），你不懂渲染吧？最终的着色是由渲染、光照模型,这些shader决定的又不是物体本身的颜色什么的等等的好么？
3、revit标准材质是在材质库中找到的你去看看SOFTWARE\\WOW6432Node\\Autodesk\\ADSKTextureLibrary\\1（1、2、3根本就没有凹凸贴图）

**Comment by hbbliyong** [comment]
1.材质里面不但凹凸会影响渲染，染色也会影响最终效果
![image](https://user-images.githubusercontent.com/6027514/148713701-95ac24da-469b-4603-816d-416f020aae09.png)
2.Revit显示有几种模式，最主要用的是着色和真实，渲染应该选的是真是。着色只有一个颜色，如果加了贴图也是看不见的，他只能根据贴图去填充一个颜色。真实能体现出凹凸贴图，浮雕之类的特殊材质。

**Comment by weiyu666** [comment]
我不太清楚你懂不懂图形学 渲染什么的,凹凸贴图 漫反射 、粗糙都会影响渲染这些都是在显存中的，至于你问凹凸贴图可以根据漫反射贴图直接用算法可以生成 _C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\Textures\1\Mats  autodesk的标准材质里面的材质库没有直接的凹凸贴图 ，至于revit的集中比如真实 线框模式什么的都是特效或者shader的管线控制，光线追踪也是；
![image](https://user-images.githubusercontent.com/22174508/148757160-208e9839-4d0c-4e6e-a805-b727e25cbf28.png)

**Comment by hbbliyong** [comment]
这种带bump的都是凹凸贴图的底图啊
![image](https://user-images.githubusercontent.com/6027514/148757562-651245bd-ccca-41e7-b3f0-33371f7361a7.png)

**Comment by hbbliyong** [comment]
我想问的是怎么能通过revit api取出这些底图

**Comment by weiyu666** [comment]
我程序写了 然后 是一般的纹理贴图属性名“unifiedbitmap程序写了 然后 是一般的纹理贴图属性名“unifiedbitmap_Bitmap” ，凹凸贴图你要看看SDK的 API文档找一下吧或者 你打断点看看是那个属性了，我有点忘记了是具体呢啦。_Bitmap” ，凹凸贴图你要看看SDK的 API文档找一下吧或者 你打断点看看是那个属性了，我有点忘记了是具体呢啦。
